In [1]:
import torch

In [2]:
x = torch.randn(3,requires_grad=True)

In [3]:
print(x)

tensor([-0.1598, -0.3783,  1.8162], requires_grad=True)


In [4]:
y = x + 2

In [5]:
print (y)

tensor([1.8402, 1.6217, 3.8162], grad_fn=<AddBackward0>)


In [6]:
z = y*y
print(z)

tensor([ 3.3863,  2.6298, 14.5632], grad_fn=<MulBackward0>)


In [7]:
z = z.mean()
print(z)

tensor(6.8598, grad_fn=<MeanBackward0>)


In [8]:
print(x.grad) 
z.backward() #dz/dx hesaplanır.
print(x.grad)

None
tensor([1.2268, 1.0811, 2.5441])


In [9]:
print(x)
x.requires_grad_(False) # grad değerinden kurtulmuş olur. Pythonda _ ile biten bir özellik var ise bu inplace demektir.
print(x)

tensor([-0.1598, -0.3783,  1.8162], requires_grad=True)
tensor([-0.1598, -0.3783,  1.8162])
